development:
  adapter: postgresql
  encoding: unicode
  database: oauth_desk_trial_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: oauth_desk_trial_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: oauth_desk_trial_production
  pool: 5
